name: Tests

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x, 16.x, 18.x]

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }}, Node ${{ matrix.node-version }}

    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt install wireless-tools
          npm install
          COV=$(npm test -- --coverage --collectCoverageFrom='./lib/**' | grep 'All files' | awk '{print $4}')
          curl -X PUT -H "Content-Type: application/json" -d '{"schemaVersion":1,"label":"coverage","message":"'$COV'%","color":"yellow","namedLogo":"jest"}' https://jsonblob.com/api/jsonBlob/1048771169276411904 
