name: Tests

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x, 16.x, 18.x]

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }}, Node ${{ matrix.node-version }}

    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm test -- --coverage --collectCoverageFrom='./lib/**' | grep 'All files'
